version: "3.8"

services:
  son_app:
    container_name: "son_app"
    build:
      context: .
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      - ./:/app
    entrypoint: dockerize
    command: flask run --host=0.0.0.0

volumes:
  dbdata:
