name: Deploy EC2

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}  # Prevents more than one instance of this workflow running at the same time

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOST_NAME : ${{ secrets.AWS_IP_ADDRESS  }}
          USER_NAME : ${{ secrets.EC2_USER_NAME  }}
          USER_PASSWORD: ${{ secrets.EC2_USER_PASSWORD }}
          APP_DIR: ${{secrets.APP_DIR}}
          SERVICE_NAME: ${{secrets.SERVICE_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
          cd ${APP_DIR} &&
          git pull &&
          echo ${USER_PASSWORD} | sudo -S systemctl restart ${SERVICE_NAME} "
